accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logout_request, name='logout'),
    path('password-reset/', views.change_password, name='change_password'),
    path('edit/<pk>/', views.edit_profile.as_view(), name='edit'),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
        path('', views.index, name='home'),
        path('profile/<slug>/', views.profile, name='profile'),
        path('memento-category/', views.memento_category, name='memcat'),
        path('memento-category/<slug>/', views.memento, name='memlist'),
        path('memento-category/memento/<pk>/', views.memento_detail, name='memento'),
        path('category-delete/<slug>/', views.delete_category, name="cat-delete"),
        path('memento-delete/<slug>/', views.delete_memento, name="mem-delete"),
        path('add-category/', views.add_category, name="catadd"),
        path('add-memento/<slug>/', views.add_memento, name='memadd'),
        path('edit-category/<pk>/', views.EditCategory.as_view(), name='catedit'),
        path('memento-all/', views.memento_list, name='memall'),
        path('edit-memento/<pk>/', views.EditMemento.as_view(), name='memedit'),
]

memento/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('main.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    birthdate = models.DateField(null=True)
    gender = models.CharField(max_length=25,choices=(('male','male'), ('female','female'), ('other','other')), null=True)
    email = models.EmailField(max_length=150, null=True)
    image = models.ImageField(upload_to="images/profile/", blank=True, null=True, default='/default/avatar.png')
    bio = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.user.username




@receiver(post_save, sender=User)
def update_profile_signal(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class SignUpForm(UserCreationForm):
    Email = forms.EmailField()
    birthdate = forms.DateField()
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ('username', 'Email', 'birthdate', 'first_name', 'last_name', 'password1', 'password2', )


class Loginform(forms.Form):
    username = forms.CharField(max_length= 25,label="Enter username")
    password = forms.CharField(max_length= 30, label='Password', widget=forms.PasswordInput)


class ProfileForm(forms.ModelForm):
   #username = forms.CharField(max_length=50, required=False, label='Username')
   #Image = forms.ImageField(required=False)

   class Meta:

       model = Profile

       fields = ( 'first_name', 'last_name', 'birthdate', 'gender', 'email', 'image', 'bio')

accounts/views.py
from django.shortcuts import render, redirect, Http404
from django.contrib.auth import login,logout, authenticate
from memento.settings import EMAIL_HOST_USER
from . import forms
from django.views.generic import UpdateView
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from .models import Profile
from django.core.mail import send_mail



def loginPage(request):

    form = forms.Loginform(request.POST or None)
    if form.is_valid():
        uservalue = form.cleaned_data.get("username")
        passwordvalue = form.cleaned_data.get("password")

        user = authenticate(username=uservalue, password=passwordvalue)
        if user is not None:
            login(request, user)


            context = {'form': form,
                       'error': 'The login has been successful'}

            return redirect('/profile/{}/'.format(request.user))
        else:
            context = {'form': form,
                       'error': 'The username and password combination is incorrect'}

            return render(request, 'login.html', context)

    else:
        context = {'form': form}
        return render(request, 'login.html', context)


@login_required
def logout_request(request):
    logout(request)
    return redirect("/")


def signup(request):
    form = forms.SignUpForm(request.POST)
    if form.is_valid():
        user = form.save()
        user.refresh_from_db()
        user.profile.birthdate = form.cleaned_data.get('birthdate')
        user.profile.first_name = form.cleaned_data.get('first_name')
        user.profile.last_name = form.cleaned_data.get('last_name')
        #user.profile.gender = form.cleaned_data.get('gender')
        user.profile.email = form.cleaned_data.get('Email')
        user.save()
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(request, user)
        send_mail(
            'Welcome To Memento',
            'Dear {}, Here we share our memories and record our private mementos in a new way! Hope you enjoy Memento ;)'.format(username),
            EMAIL_HOST_USER,
            ['{}'.format(user.profile.email)],
            fail_silently=False,
        )
        return redirect('/profile/{}/'.format(request.user))
    else:
        form = forms.SignUpForm()
    return render(request, 'signup.html', {'form': form})

@login_required()
def change_password(request):
    profile = Profile.objects.get(id=request.user.id)
    pro = Profile.objects.filter(user=request.user)
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated!')
            print(profile.email)
            send_mail(
                'Password Was Successfully Updated',
                'Dear {}, You have Successfully Updated your Password\n\n<Memento Team>'.format(
                    request.user),
                EMAIL_HOST_USER,
                ['{}'.format(profile.email)],
                fail_silently=False,
            )
            return redirect('/profile/{}/'.format(request.user))
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'resetpass.html', {
        'form': form, 'profile': pro
    })



class edit_profile(UpdateView):


        model = Profile
        form_class = forms.ProfileForm
        template_name = 'profile_edit.html'



        def get_success_url(self):
                return '/profile/{}/'.format(self.request.user)




        def get(self,request,pk):

            if int(request.user.id) == int(pk):
                init = Profile.objects.get(pk=pk)
                pro = Profile.objects.filter(user=request.user)
                form = forms.ProfileForm( initial={"username":request.user, "first_name": init.first_name,
                                                   "last_name": init.last_name, "birthdate": init.birthdate,
                                                   "gender": init.gender, "email": init.email, "image": init.image,
                                                   "bio": init.bio})


                return render(request,'profile_edit.html',{'profile': pro, 'form': form})
            else:
                raise Http404




        def put(self, request, pk, *args, **kwargs):


            if int(request.user.id) == int(pk):

                form = forms.ProfileForm(request.POST, request.FILES)

                if form.is_valid():

                    first_name = request.POST.get('first_name')
                    last_name = request.POST.get('last_name')
                    birthdate = request.POST.get('birthdate')
                    email = request.POST.get('email')
                    bio = request.POST.get('bio')
                    gender = request.POST.get('gender')

                    profile = Profile.objects.get(pk=pk)


                    profile.image =request.FILES['image']

                    profile.refresh_from_db()

                    profile.first_name = first_name
                    profile.last_name = last_name


                    profile.birthdate = birthdate
                    profile.bio = bio
                    profile.email = email
                    profile.gender = gender

                    profile.save()


                    return redirect('/profile/{}/'.format(request.user))


            else:
                raise Http404

accounts/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="/static/fonts/material-icon/css/material-design-iconic-font.min.css">

    <!-- Main css -->
    <link rel="stylesheet" href="/static/css/style.css">
</head>


<body style="background-color:#b2c7a9">

    <div class="main" style="background-color:#b2c7a9">

    <a href="/" class="signup-image-link"><center><h1><font face = "Bedrock" size = "15">Memento</font></h1></center></a>
    <p></p>
        <section class="sign-in">

            <div class="container">

                <center><h3><font color="red">{{error}}</font></h3></center>
                <div class="signin-content">
                    <div class="signin-image">
                        <figure><img src="/static/images/signin-image.jpg" alt="sing up image"></figure>
                        <a href="/accounts/signup/" class="signup-image-link">Create an account</a>
                    </div>

                    <div class="signin-form">
                        <h2 class="form-title">Login</h2>
                        <form method="POST" class="register-form" id="login-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <label ><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="username" id="username_id" placeholder="Username"/>
                            </div>
                            <div class="form-group">
                                <label><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="password" id="password_id" placeholder="Password"/>
                            </div>
                            <div class="form-group">
                                <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                                <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>
                            </div>
                            <div class="form-group form-button">
                                <input type="submit" name="signin" id="signin" class="form-submit" value="Log in"/>
                            </div>
                        </form>


                    </div>
                </div>
            </div>
        </section>


    </div>

    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/js/main.js"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

accounts/templates/profile_edit.html
{% extends "header.html" %}

{% block content %}

<style>
    .divL {
      float: left;
      box-sizing: border-box;
      width: 50%;
      padding: 10px;
    }

    .divR {
      float: right;
      box-sizing: border-box;
      width: 50%;
      padding: 60px;

    }

    .button {
  display: inline-block;
  padding: 15px 25px;
  font-size: 24px;
  cursor: pointer;
  text-align: center;
  text-decoration: none;
  outline: none;
  color: #fff;
  background-color: #454f66;
  border: none;
  border-radius: 15px;
  box-shadow: 0 9px #999;
}

.button:hover {background-color: #434757}

.button:active {
  background-color: #434757;
  box-shadow: 0 5px #666;
  transform: translateY(4px);

    </style>

<br>
<section class="about full-screen d-lg-flex justify-content-center align-items-center" id="about">
    <div class="container">
    <div class="container" style="background-color:#828fc4; border-radius:60px">
        <div class="row">



        <br></br>


        <div class="container" style="background-color: #1d2433; border-radius: 12px">
            <center><h3 style="color:#e1e3e8"><span>Edit Your Profile</span></h3></center>
            <br></br>

            {% for p in profile %}

            <center><img src="/media/{{p.image}}" alt="Avatar" style="border-radius: 50%; width:200px; height:200px">

            <br></br>
            </center>

<br>
<br>

        <div class="container">
            <center>
            <div class="container">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                {{ form.non_field_errors }}
                 {{ form.image.errors }}

                <center><input class="button" type="submit">Submit</input></center>

            </form>
    {% endfor %}
        </div>
        </center>
        </div>
        </div>
        </div>
    </div>
</div>
</section>

{% endblock %}

accounts/templates/resetpass.html
{% extends "header.html" %}


{% block content %}
<style>
.button {
  display: inline-block;
  padding: 15px 25px;
  font-size: 24px;
  cursor: pointer;
  text-align: center;
  text-decoration: none;
  outline: none;
  color: #fff;
  background-color: #585e75;
  border: none;
  border-radius: 15px;
  box-shadow: 0 9px #999;
}

.button:hover {background-color: #434757}

.button:active {
  background-color: #434757;
  box-shadow: 0 5px #666;
  transform: translateY(4px);
}
</style>
<br>
<br>
<br>
<div class="container">
    <div class="container" style="background-color:#8b8d94;border-radius:40px;">
        <br>
        <br>
    <form method="post">
        {% csrf_token %}

        {{form.as_p}}
        <br>
        <center><button class="button" type="submit">Submit</button></center>
    </form>
    </div>
</div>

<br>
<br>
<br>
<br>


{% endblock %}

accounts/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="/static/fonts/material-icon/css/material-design-iconic-font.min.css">

    <!-- Main css -->
    <link rel="stylesheet" href="/static/css/style.css">
</head>
<body style="background-color:#b2b7c2">

    <div class="main" style="background-color:#b2b7c2">

        <a href="/" class="signup-image-link"><center><h1><font face = "Bedrock" size = "15">Memento</font></h1></center></a>

        <!-- Sign up form -->
        <section class="signup">
            <div class="container">

                <div class="signup-content">
                    <div class="signup-form">
                        <h2 class="form-title">Sign up</h2>
                        <form method="POST" class="register-form" id="register-form">
                            {% csrf_token %}
                            <div class="form-group">
                                <label><i class="zmdi zmdi-d"></i></label>
                                <input type="text" name="first_name" id="id_first_name" placeholder="Your First Name"/>
                            </div>
                            <div class="form-group">
                                <label><i class="zmdi zmdi-date"></i></label>
                                <input type="text" name="last_name" id="id_last_name" placeholder="Your Last Name"/>
                            </div>
                            <div class="form-group">
                                <label><i class="zmdi zmdi-date"></i></label>
                                <input type="text" name="birthdate" id="id_birthdate" placeholder="Your Birth Date"/>
                            </div>
                            <div class="form-group">
                                <label><i class="zmdi zmdi-email"></i></label>
                                <input type="email" name="Email" id="id_Email" placeholder="Your Email"/>
                            </div>
                            <div class="form-group">
                                <label><i class="zmdi zmdi-account material-icons-name"></i></label>
                                <input type="text" name="username" id="id_username" placeholder="Your Username"/>
                            </div>
                            <div class="form-group">
                                <label><i class="zmdi zmdi-lock"></i></label>
                                <input type="password" name="password1" id="id_password1" placeholder="Password"/>
                            </div>
                            <div class="form-group">
                                <label><i class="zmdi zmdi-lock-outline"></i></label>
                                <input type="password" name="password2" id="id_password2" placeholder="Repeat your password"/>
                            </div>

                            <div class="form-group form-button">
                                <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                            </div>
                        </form>
                    </div>
                    <div class="signup-image">
                        <figure><img src="/static/images/signup-image.jpg" alt="sing up image"></figure>
                        <a href="/accounts/login/" class="signup-image-link">I am already member</a>
                    </div>
                </div>
            </div>
        </section>


    </div>

    <!-- JS -->
    <script src="/static/vendor/jquery/jquery.min.js"></script>
    <script src="/static/js/main.js"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>